name: push workflow
run-name: push workflow
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
  codeql:
    runs-on: ubuntu-latest
    steps:
      - name: CodeQL
        run: |
          wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.16.4/codeql-bundle-linux64.tar.gz
          tar -xvf codeql-bundle-linux64.tar.gz
          cd codeql
          ls -la
          echo "PRUEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
          ./codeql --version
